import React from "react";
import {
  AbsoluteFill,
  Html5Audio,
  interpolate,
  Sequence,
  staticFile,
} from "remotion";
import {
  SceneApartment,
  SceneCause,
  SceneCTA,
  SceneEnd,
  SceneHook,
  SceneOffer,
  SceneSurprise,
  SceneUrgency,
} from "./scenes";
import { COLORS, DURATION, FONT, SCENES } from "./theme";

export { DURATION as DREAM9_DURATION, FPS as DREAM9_FPS } from "./theme";

const TIMELINE = [
  { name: "Hook", Component: SceneHook, ...SCENES.hook },
  { name: "Surprise", Component: SceneSurprise, ...SCENES.surprise },
  { name: "Apartment", Component: SceneApartment, ...SCENES.apartment },
  { name: "1+1 offer", Component: SceneOffer, ...SCENES.offer },
  { name: "Cause", Component: SceneCause, ...SCENES.cause },
  { name: "Urgency", Component: SceneUrgency, ...SCENES.urgency },
  { name: "CTA", Component: SceneCTA, ...SCENES.cta },
  { name: "End card", Component: SceneEnd, ...SCENES.end },
];

// Sound effects (absolute frames), generated by
// scripts/generate-dream9-audio.mjs. Each one sits on a cut or text hit.
export const SFX: {
  file: string;
  at: number;
  volume: number;
  length?: number;
}[] = [
  { file: "bassdrop", at: 0, volume: 0.9 },
  { file: "swoosh", at: 21, volume: 0.6 },
  { file: "swoosh", at: 45, volume: 0.6 },
  { file: "swoosh", at: 87, volume: 0.6 },
  { file: "pop", at: 92, volume: 0.6 },
  { file: "cash", at: 100, volume: 0.8 },
  { file: "pop", at: 110, volume: 0.6 },
  { file: "swoosh", at: 177, volume: 0.6 },
  { file: "pop", at: 186, volume: 0.5 },
  { file: "pop", at: 198, volume: 0.5 },
  { file: "pop", at: 210, volume: 0.5 },
  { file: "pop", at: 224, volume: 0.6 },
  { file: "pop", at: 242, volume: 0.6 },
  { file: "swoosh", at: 250, volume: 0.4 },
  { file: "pop", at: 260, volume: 0.6 },
  { file: "riser", at: 240, volume: 0.5 },
  { file: "swoosh", at: 297, volume: 0.7 },
  { file: "ticker", at: 310, volume: 0.35, length: 80 },
  { file: "swoosh", at: 328, volume: 0.35 },
  { file: "swoosh", at: 358, volume: 0.35 },
  { file: "bassdrop", at: 390, volume: 0.8 },
  { file: "swoosh", at: 418, volume: 0.35 },
  { file: "swoosh", at: 448, volume: 0.35 },
  { file: "swoosh", at: 477, volume: 0.6 },
  { file: "swoosh", at: 508, volume: 0.6 },
  { file: "pop", at: 516, volume: 0.7 },
  { file: "pop", at: 522, volume: 0.7 },
  { file: "stamp", at: 535, volume: 0.8 },
  { file: "pop", at: 548, volume: 0.5 },
  { file: "bassdrop", at: 570, volume: 0.8 },
  { file: "ticktock", at: 690, volume: 0.7 },
  { file: "swoosh", at: 777, volume: 0.6 },
  { file: "click", at: 816, volume: 0.9 },
  { file: "pop", at: 824, volume: 0.7 },
  { file: "pop", at: 850, volume: 0.5 },
  { file: "bassdrop", at: 900, volume: 0.8 },
  { file: "pop", at: 936, volume: 0.6 },
];

const musicVolume = (f: number) =>
  interpolate(f, [0, 6, DURATION - 30, DURATION], [0, 0.55, 0.55, 0], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  });

export const DreamRaffle9: React.FC = () => (
  <AbsoluteFill
    style={{ backgroundColor: COLORS.ink, direction: "rtl", fontFamily: FONT }}
  >
    <Html5Audio
      src={staticFile("dream9/audio/music.mp3")}
      volume={musicVolume}
    />
    {SFX.map(({ file, at, volume, length }) => (
      <Sequence
        key={`${file}-${at}`}
        from={at}
        durationInFrames={length}
        name={`SFX: ${file}`}
        layout="none"
      >
        <Html5Audio
          src={staticFile(`dream9/audio/${file}.mp3`)}
          volume={volume}
        />
      </Sequence>
    ))}
    {TIMELINE.map(({ name, Component, from, duration }) => (
      <Sequence key={name} name={name} from={from} durationInFrames={duration}>
        <Component />
      </Sequence>
    ))}
  </AbsoluteFill>
);
