import React from "react";
import {
  AbsoluteFill,
  Html5Audio,
  interpolate,
  Sequence,
  staticFile,
} from "remotion";
import { BrandStripe, SceneFade } from "./components";
import {
  SceneAmenities,
  SceneApartments,
  SceneChoice,
  SceneCTA,
  SceneHero,
  SceneLocation,
} from "./scenes";
import { COLORS, CROSSFADE, DURATION, FONT, SCENES } from "./theme";

export { DURATION as KARDAN_DURATION, FPS as KARDAN_FPS } from "./theme";

const TIMELINE = [
  { name: "Hero", Component: SceneHero, ...SCENES.hero },
  { name: "Location", Component: SceneLocation, ...SCENES.location },
  { name: "Tower or boutique", Component: SceneChoice, ...SCENES.choice },
  { name: "Amenities", Component: SceneAmenities, ...SCENES.amenities },
  { name: "Apartments", Component: SceneApartments, ...SCENES.apartments },
  { name: "CTA", Component: SceneCTA, ...SCENES.cta },
];

export const KardanUziel: React.FC = () => (
  <AbsoluteFill
    style={{ backgroundColor: COLORS.ink, direction: "rtl", fontFamily: FONT }}
  >
    {/* Original track generated by scripts/generate-kardan-music.mjs */}
    <Html5Audio
      src={staticFile("kardan/music.mp3")}
      volume={(f) =>
        interpolate(f, [0, 8, DURATION - 45, DURATION], [0, 0.8, 0.8, 0], {
          extrapolateLeft: "clamp",
          extrapolateRight: "clamp",
        })
      }
    />
    {TIMELINE.map(({ name, Component, from, duration }, i) => {
      const isLast = i === TIMELINE.length - 1;
      // Each scene runs CROSSFADE frames into the next, which fades in on top.
      return (
        <Sequence
          key={name}
          name={name}
          from={from}
          durationInFrames={isLast ? duration : duration + CROSSFADE}
        >
          <SceneFade fadeIn={i > 0}>
            <Component />
          </SceneFade>
        </Sequence>
      );
    })}
    <BrandStripe />
  </AbsoluteFill>
);
