import React from "react";
import {
  AbsoluteFill,
  Html5Audio,
  interpolate,
  Sequence,
  staticFile,
} from "remotion";
import { CutFlash } from "./components";
import {
  SceneAskClip,
  SceneBonus,
  SceneCauseClip,
  SceneCTA,
  SceneFollowClip,
  SceneHook,
  ScenePrize,
} from "./scenes";
import { COLORS, DURATION, FONT, MEDIA, SCENES } from "./theme";

export { DURATION as DREAM_DURATION, FPS as DREAM_FPS } from "./theme";

const TIMELINE = [
  { name: "Hook", Component: SceneHook, ...SCENES.hook },
  { name: "Ask (footage)", Component: SceneAskClip, ...SCENES.askClip },
  { name: "Prize + 9th year", Component: ScenePrize, ...SCENES.prize },
  { name: "Cause (footage)", Component: SceneCauseClip, ...SCENES.causeClip },
  { name: "Bonus", Component: SceneBonus, ...SCENES.bonus },
  {
    name: "Follow (footage)",
    Component: SceneFollowClip,
    ...SCENES.followClip,
  },
  { name: "CTA", Component: SceneCTA, ...SCENES.cta },
];

const CLIPS = [SCENES.askClip, SCENES.causeClip, SCENES.followClip];

// Music sits high under the graphics and ducks under the market footage,
// where the original street audio carries the scene.
const musicVolume = (f: number) => {
  const inClip = CLIPS.reduce(
    (acc, c) =>
      Math.max(
        acc,
        interpolate(
          f,
          [
            c.from - 6,
            c.from + 6,
            c.from + c.duration - 6,
            c.from + c.duration + 6,
          ],
          [0, 1, 1, 0],
          { extrapolateLeft: "clamp", extrapolateRight: "clamp" },
        ),
      ),
    0,
  );
  const fade = interpolate(f, [0, 6, DURATION - 30, DURATION], [0, 1, 1, 0], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  });
  return fade * interpolate(inClip, [0, 1], [0.6, 0.1]);
};

export const DreamLottery: React.FC = () => (
  <AbsoluteFill
    style={{ backgroundColor: COLORS.deep, direction: "rtl", fontFamily: FONT }}
  >
    {/* Original track generated by scripts/generate-music.mjs */}
    <Html5Audio src={staticFile(MEDIA.music)} loop volume={musicVolume} />
    {TIMELINE.map(({ name, Component, from, duration }) => (
      <Sequence key={name} name={name} from={from} durationInFrames={duration}>
        <Component />
        <CutFlash />
      </Sequence>
    ))}
  </AbsoluteFill>
);
