import React from "react";
import {
  AbsoluteFill,
  Html5Audio,
  interpolate,
  Sequence,
  staticFile,
  useVideoConfig,
} from "remotion";
import { CutFlash } from "./components";
import {
  SceneAskClip,
  SceneBonus,
  SceneCauseClip,
  SceneCTA,
  SceneFollowClip,
  SceneHook,
  ScenePrize,
} from "./scenes";
import { COLORS, CUTS, CutName, FONT, MEDIA, SCENES, SceneKey } from "./theme";

export { cutDuration as dreamDuration, FPS as DREAM_FPS } from "./theme";

const SCENE_INFO: Record<
  SceneKey,
  { name: string; Component: React.FC; footage?: boolean }
> = {
  hook: { name: "Hook", Component: SceneHook },
  askClip: { name: "Ask (footage)", Component: SceneAskClip, footage: true },
  prize: { name: "Prize + 9th year", Component: ScenePrize },
  causeClip: {
    name: "Cause (footage)",
    Component: SceneCauseClip,
    footage: true,
  },
  bonus: { name: "Bonus", Component: SceneBonus },
  followClip: {
    name: "Follow (footage)",
    Component: SceneFollowClip,
    footage: true,
  },
  cta: { name: "CTA", Component: SceneCTA },
};

const timeline = (cut: CutName) => {
  let from = 0;
  return CUTS[cut].map((key) => {
    const entry = { key, from, duration: SCENES[key].duration };
    from += entry.duration;
    return entry;
  });
};

// Music sits high under the graphics and ducks under the market footage,
// where the original street audio carries the scene.
const musicVolume =
  (clips: { from: number; duration: number }[], total: number) =>
  (f: number) => {
    const inClip = clips.reduce(
      (acc, c) =>
        Math.max(
          acc,
          interpolate(
            f,
            [
              c.from - 6,
              c.from + 6,
              c.from + c.duration - 6,
              c.from + c.duration + 6,
            ],
            [0, 1, 1, 0],
            { extrapolateLeft: "clamp", extrapolateRight: "clamp" },
          ),
        ),
      0,
    );
    const fade = interpolate(f, [0, 6, total - 30, total], [0, 1, 1, 0], {
      extrapolateLeft: "clamp",
      extrapolateRight: "clamp",
    });
    return fade * interpolate(inClip, [0, 1], [0.6, 0.1]);
  };

export const DreamLottery: React.FC<{ cut: CutName }> = ({ cut }) => {
  const { durationInFrames } = useVideoConfig();
  const scenes = timeline(cut);
  const clips = scenes.filter((s) => SCENE_INFO[s.key].footage);
  return (
    <AbsoluteFill
      style={{
        backgroundColor: COLORS.deep,
        direction: "rtl",
        fontFamily: FONT,
      }}
    >
      {/* Original track generated by scripts/generate-music.mjs */}
      <Html5Audio
        src={staticFile(MEDIA.music)}
        loop
        volume={musicVolume(clips, durationInFrames)}
      />
      {scenes.map(({ key, from, duration }) => {
        const { name, Component } = SCENE_INFO[key];
        return (
          <Sequence
            key={key}
            name={name}
            from={from}
            durationInFrames={duration}
          >
            <Component />
            <CutFlash />
          </Sequence>
        );
      })}
    </AbsoluteFill>
  );
};
