import React from "react";
import { AbsoluteFill, Html5Audio, interpolate, staticFile } from "remotion";
import {
  linearTiming,
  TransitionPresentation,
  TransitionSeries,
} from "@remotion/transitions";
import { fade } from "@remotion/transitions/fade";
import { slide } from "@remotion/transitions/slide";
import { wipe } from "@remotion/transitions/wipe";
import { BrandStripe } from "./components";
import {
  SceneCTA,
  SceneHook,
  SceneInteriors,
  SceneLocation,
  SceneProject,
  SceneTrust,
} from "./scenes";
import { COLORS, FONT_FAMILY } from "./theme";

export const UZIEL_FPS = 30;
const T = 15; // transition length in frames

// Every scene except the last is padded by T, so after the overlaps the
// scenes start at 0, 4, 9, 14, 20 and 24s — the bar lines of the music
// track (scripts/generate-uziel-music.mjs) — and the total is 30s.
const SCENES = [
  { Component: SceneHook, frames: 120 + T },
  { Component: SceneLocation, frames: 150 + T },
  { Component: SceneProject, frames: 150 + T },
  { Component: SceneInteriors, frames: 180 + T },
  { Component: SceneTrust, frames: 120 + T },
  { Component: SceneCTA, frames: 180 },
];

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const TRANSITIONS: TransitionPresentation<any>[] = [
  wipe({ direction: "from-right" }),
  slide({ direction: "from-bottom" }),
  fade(),
  slide({ direction: "from-right" }),
  fade(),
];

export const UZIEL_DURATION =
  SCENES.reduce((sum, s) => sum + s.frames, 0) - TRANSITIONS.length * T;

export const UzielLeadAd: React.FC = () => {
  return (
    <AbsoluteFill
      style={{
        direction: "rtl",
        fontFamily: FONT_FAMILY,
        backgroundColor: COLORS.slateDeep,
      }}
    >
      {/* Original track generated by scripts/generate-uziel-music.mjs */}
      <Html5Audio
        src={staticFile("uziel/audio/music.mp3")}
        volume={(f) =>
          interpolate(
            f,
            [0, 10, UZIEL_DURATION - 30, UZIEL_DURATION],
            [0, 0.8, 0.8, 0],
            { extrapolateLeft: "clamp", extrapolateRight: "clamp" },
          )
        }
      />
      <TransitionSeries>
        {SCENES.map(({ Component, frames }, i) => (
          <React.Fragment key={i}>
            <TransitionSeries.Sequence durationInFrames={frames}>
              <Component />
            </TransitionSeries.Sequence>
            {i < TRANSITIONS.length ? (
              <TransitionSeries.Transition
                presentation={TRANSITIONS[i]}
                timing={linearTiming({ durationInFrames: T })}
              />
            ) : null}
          </React.Fragment>
        ))}
      </TransitionSeries>
      <BrandStripe />
      <div
        style={{
          position: "absolute",
          top: 48,
          right: 52,
          fontSize: 30,
          fontWeight: 700,
          color: "rgba(255,255,255,0.9)",
          textShadow: "0 2px 8px rgba(0,0,0,0.5)",
        }}
      >
        בס״ד
      </div>
    </AbsoluteFill>
  );
};
