import React from "react";
import { Html5Audio, interpolate, Sequence, staticFile } from "remotion";
import {
  CTA_POP_FRAME,
  DURATION,
  FPS,
  HEARTBEAT_PERIOD,
  SCENES,
  VOICEOVER_FILE,
  voStart,
} from "./theme";

// Background score volume, per the audio brief:
//   intro (scenes 1–2)       soft piano/strings          0.25
//   turning point (scene 3)  building orchestral swells  → 0.45
//   Zohar reveal → end       triumphant climax           → 0.60, 2s fade-out
const musicVolume = (f: number) =>
  interpolate(
    f,
    [
      0,
      10,
      SCENES.turning.from,
      SCENES.turning.from + 30,
      SCENES.zohar.from,
      SCENES.zohar.from + 15,
      DURATION - 2 * FPS,
      DURATION,
    ],
    [0, 0.25, 0.25, 0.45, 0.45, 0.6, 0.6, 0],
    { extrapolateLeft: "clamp", extrapolateRight: "clamp" },
  );

// Music sits lower under a voiceover so the narration stays clear.
const VOICEOVER_DUCK = 0.45;

// Start the heartbeat about a second before "הלב שלו", on a beat boundary
// so it stays in phase with the visual pulse in Scene 2.
const heartbeatFrom =
  SCENES.struggle.from +
  Math.max(
    0,
    Math.round((voStart("l4") - 30 - SCENES.struggle.from) / HEARTBEAT_PERIOD),
  ) *
    HEARTBEAT_PERIOD;

// Riser is 5s long and should peak on the Zohar reveal.
const RISER_LENGTH = 5 * FPS;

// Sound effects, all generated by scripts/generate-zohar-audio.mjs.
const SFX: { file: string; from: number; volume: number }[] = [
  { file: "rumble", from: 0, volume: 0.6 },
  { file: "heartbeat", from: heartbeatFrom, volume: 0.8 },
  { file: "riser", from: SCENES.zohar.from - RISER_LENGTH, volume: 0.45 },
  { file: "chime", from: SCENES.zohar.from, volume: 0.6 },
  { file: "pop", from: CTA_POP_FRAME, volume: 0.7 },
];

export const AudioLayer: React.FC = () => {
  return (
    <>
      <Html5Audio
        src={staticFile("zohar/audio/music.mp3")}
        volume={(f) => musicVolume(f) * (VOICEOVER_FILE ? VOICEOVER_DUCK : 1)}
      />
      {SFX.map(({ file, from, volume }) => (
        <Sequence key={file} from={from} name={`SFX: ${file}`} layout="none">
          <Html5Audio
            src={staticFile(`zohar/audio/${file}.mp3`)}
            volume={volume}
          />
        </Sequence>
      ))}
      {VOICEOVER_FILE ? <Html5Audio src={staticFile(VOICEOVER_FILE)} /> : null}
    </>
  );
};
