import React from "react";
import { Html5Audio, interpolate, Sequence, staticFile } from "remotion";
import { DURATION, FPS, SCENES, VOICEOVER_FILE } from "./theme";

// Background score volume, per the audio brief:
//   0–270    soft piano/strings          0.25
//   270–420  building orchestral swells  → 0.45
//   420–900  triumphant climax           → 0.60, fading out over the last 2s
const musicVolume = (f: number) =>
  interpolate(
    f,
    [0, 10, 270, 300, 420, 435, DURATION - 2 * FPS, DURATION],
    [0, 0.25, 0.25, 0.45, 0.45, 0.6, 0.6, 0],
    { extrapolateLeft: "clamp", extrapolateRight: "clamp" },
  );

// Music sits lower under a voiceover so the narration stays clear.
const VOICEOVER_DUCK = 0.55;

// Sound effects, all generated by scripts/generate-zohar-audio.mjs.
const SFX: { file: string; from: number; volume: number }[] = [
  { file: "rumble", from: 0, volume: 0.9 },
  { file: "heartbeat", from: SCENES.struggle.from, volume: 0.8 },
  { file: "riser", from: SCENES.turning.from, volume: 0.45 },
  { file: "chime", from: SCENES.zohar.from, volume: 0.6 },
  { file: "pop", from: SCENES.cta.from, volume: 0.7 },
];

export const AudioLayer: React.FC = () => {
  return (
    <>
      <Html5Audio
        src={staticFile("zohar/audio/music.mp3")}
        volume={(f) => musicVolume(f) * (VOICEOVER_FILE ? VOICEOVER_DUCK : 1)}
      />
      {SFX.map(({ file, from, volume }) => (
        <Sequence key={file} from={from} name={`SFX: ${file}`} layout="none">
          <Html5Audio
            src={staticFile(`zohar/audio/${file}.mp3`)}
            volume={volume}
          />
        </Sequence>
      ))}
      {VOICEOVER_FILE ? <Html5Audio src={staticFile(VOICEOVER_FILE)} /> : null}
    </>
  );
};
