import React from "react";
import {
  AbsoluteFill,
  Html5Audio,
  interpolate,
  Sequence,
  staticFile,
} from "remotion";
import { SceneFade } from "./components";
import {
  SceneBonus,
  SceneCause,
  SceneCTA,
  SceneHook,
  SceneOffer,
  ScenePrize,
  SceneSuper,
} from "./scenes";
import { COLORS, CROSSFADE, DURATION, FONT, SCENES, SceneName } from "./theme";

export { DURATION as RAFFLE_DURATION, FPS as RAFFLE_FPS } from "./theme";

const TIMELINE: { name: SceneName; Component: React.FC }[] = [
  { name: "hook", Component: SceneHook },
  { name: "prize", Component: ScenePrize },
  { name: "super", Component: SceneSuper },
  { name: "offer", Component: SceneOffer },
  { name: "bonus", Component: SceneBonus },
  { name: "cause", Component: SceneCause },
  { name: "cta", Component: SceneCTA },
];

// Music sits low so the narration stays clear.
const MUSIC_VOLUME = 0.22;

export const DreamRaffle: React.FC = () => (
  <AbsoluteFill
    style={{
      backgroundColor: COLORS.cocoa,
      direction: "rtl",
      fontFamily: FONT,
    }}
  >
    {/* Original track generated by scripts/generate-zohar-audio.mjs */}
    <Html5Audio
      src={staticFile("zohar/audio/music.mp3")}
      volume={(f) =>
        interpolate(
          f,
          [0, 10, DURATION - 45, DURATION],
          [0, MUSIC_VOLUME, MUSIC_VOLUME, 0],
          { extrapolateLeft: "clamp", extrapolateRight: "clamp" },
        )
      }
    />
    {TIMELINE.map(({ name, Component }, i) => {
      const { from, duration, voFrom } = SCENES[name];
      const isLast = i === TIMELINE.length - 1;
      return (
        <React.Fragment key={name}>
          {/* Each scene runs CROSSFADE frames into the next, which fades in on top. */}
          <Sequence
            name={`Scene: ${name}`}
            from={from}
            durationInFrames={isLast ? duration : duration + CROSSFADE}
          >
            <SceneFade fadeIn={i > 0}>
              <Component />
            </SceneFade>
          </Sequence>
          <Sequence name={`VO: ${name}`} from={voFrom} layout="none">
            <Html5Audio src={staticFile(`raffle/vo/${name}.mp3`)} />
          </Sequence>
        </React.Fragment>
      );
    })}
  </AbsoluteFill>
);
